//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparkCogingChallenge.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pay
    {
        public int Id_pay { get; set; }
        public string Concept { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public int Id_user { get; set; }
        public bool Active { get; set; }
    
        public virtual User User { get; set; }
    }
}
